angular.module("pu.task",
    [
        'pu.task.services',
        'pu.task.controllers',
        'pu.task.directives'
    ]);
angular.module('pu.task.services',[]);
angular.module('pu.task.controllers',[]);
angular.module('pu.task.directives',[]);