'use strict';

// Declare app level module which depends on views, and components
angular.module('app', [
    'ngCookies',
    'ngSanitize',
    'ngMessages',
    'ui.router',
    'restangular',
    'ui.bootstrap',
    'ui.select',
    'ui.load',
    'toaster',
    'jcs-autoValidate',
    'angularFileUpload',
    'ui.calendar',
    'pu.system',
    'pu.access',
    'pu.utils',
    'pu.workflow',
    'pu.product',
    'pu.apply',
    'pu.car',
    'pu.task',
    'pu.file',
    'pu.gps',
    'pu.form',
    'pu.contract',
    'pu.query',
    'pu.holiday',
    'pu.charge',
    'pu.loanquery',
    'pu.publicrepay',
    'pu.loantask',
    'pu.settle',
    'pu.alterrepaydate',
    'pu.refund',
    'pu.remission'
])
